{'name': "investasi",
 'version': "12.0.0",
 'author': "rafif",
 'website': "rafif@gmail.com",
 'summary': "it is a investasi module",
 'description': """ blablabla.""",
 'depends': ['base', 'account', 'purchase', 'product', 'sale', 'website'],
 'data': [
           'security/user_groups.xml',
       'security/ir.model.access.csv',
       # 'wizard/tes_wizard_view.xml',
         'views/investasi.xml',
         'views/investasi_detail_sequence.xml',
        #  'views/website_form.xml',
       #    'reports/nilai_kelas.xml',
       #    'reports/report.xml',
          ],
 'demo': [],
 'image': [],
 'license': 'AGPL-3',
 'installable': True,
 'application': True,
 'auto_install': False,

 }